type Query {
  spot(id: String!): Spot
  spots(bounds: BoundsInput!): [Spot!]!
}

type Spot {
  id: ID!
  userId: String!
  latitude: Float!
  longitude: Float!
  address: String!
  image: String!
  publicId: String!
  appetizer: String!
  entree: String!
  drink: String!
  nearby: [Spot!]!
}

input BoundsInput {
  sw: CoordinatesInput!
  ne: CoordinatesInput!
}

input CoordinatesInput {
  latitude: Float!
  longitude: Float!
}

type Mutation {
  createImageSignature: ImageSignature!
  createSpot(input: SpotInput!): Spot
  updateSpot(input: SpotInput!, id: String!): Spot
  deleteSpot(id: String!): Boolean!
}

type ImageSignature {
  signature: String!
  timestamp: Int!
}

input SpotInput {
  address: String!
  image: String!
  coordinates: CoordinatesInput!
  appetizer: String!
  entree: String!
  drink: String!
}